#!/usr/bin/env python3
"""
Manual script to run the resume scraper
Customize the parameters below and run: python run_scraper.py
"""

from scraper import ResumeScraper, SearchConfig

if __name__ == "__main__":
    # ========================================
    # CUSTOMIZE YOUR SEARCH HERE
    # ========================================

    config = SearchConfig(
        job_titles=[
            "software engineer",
            "software developer",
        ],
        seniority_levels=[
            "intern",
        ],
        file_types=["pdf"],  # PDF only - no wasted DOCX queries!
        companies=[
            "Google",
            "Two Sigma",
            "Blackstone",
            "Nvidia",
            "Microsoft",
            "Atlassian",
            "Apple",
            "Uber",
            "OpenAI",
            "Lyft",
            "Amazon",
            "Netflix",
            "JPMorgan Chase",
            "Meta",
            "Facebook",
            "Tesla",
            "Stripe",
            "Airbnb",
            "Salesforce",
            "Oracle",
            "Adobe",
            "IBM",
            "Intel",
            "Qualcomm",
            "Twitter",
            "X Corp",
            "LinkedIn",
            "Snapchat",
            "Pinterest",
            "Reddit",
            "Dropbox",
            "Spotify",
            "Coinbase",
            "Robinhood",
            "DoorDash",
            "Instacart",
            "Walmart",
            "Target",
            "Goldman Sachs",
            "Morgan Stanley",
            "Citadel",
            "Jane Street",
            "Hudson River Trading",
            "DE Shaw",
            "Bridgewater",
            "McKinsey",
            "BCG",
            "Bain",
            "Palantir",
            "SpaceX",
            "Databricks",
            "Snowflake",
            # Additional tech companies
            "Roblox",
            "Discord",
            "Twitch",
            "Shopify",
            "Square",
            "Block",
            "PayPal",
            "Venmo",
            "Zoom",
            "Slack",
            "Figma",
            "Canva",
            "Notion",
            "Asana",
            "Monday.com",
            "Atlassian",
            "GitHub",
            "GitLab",
            "Docker",
            "HashiCorp",
            "Datadog",
            "Splunk",
            "Elastic",
            "MongoDB",
            "Redis",
            "Confluent",
            "Cloudflare",
            "Fastly",
            "Akamai",
            "Vercel",
            "Netlify",
            "Heroku",
            # Finance & Trading
            "Credit Suisse",
            "UBS",
            "Barclays",
            "Bank of America",
            "Citi",
            "Wells Fargo",
            "Charles Schwab",
            "Fidelity",
            "Vanguard",
            "BlackRock",
            "Renaissance Technologies",
            "AQR Capital",
            "Millennium Management",
            "Point72",
            "Jump Trading",
            "Optiver",
            "IMC Trading",
            "Flow Traders",
            "Susquehanna (SIG)",
            "DRW",
            "Virtu Financial",
            # More tech startups
            "Plaid",
            "Brex",
            "Chime",
            "Affirm",
            "Klarna",
            "Gusto",
            "Rippling",
            "Checkr",
            "Flexport",
            "Convoy",
            "Cruise",
            "Waymo",
            "Zoox",
            "Aurora",
            "Nuro",
            "Anduril",
            "Scale AI",
            "OpenAI",
            "Anthropic",
            "Cohere",
            "Hugging Face",
            "Runway",
            "Midjourney",
            "Stability AI",
            # Enterprise tech
            "SAP",
            "ServiceNow",
            "Workday",
            "Okta",
            "Auth0",
            "Twilio",
            "SendGrid",
            "Segment",
            "Amplitude",
            "Mixpanel",
            "LaunchDarkly",
            "PagerDuty",
            "New Relic",
            "Sumo Logic",
            # Gaming
            "Epic Games",
            "Riot Games",
            "Valve",
            "Blizzard",
            "Activision",
            "EA",
            "Ubisoft",
            "Unity",
            "Unreal Engine",
            # Cloud & Infrastructure
            "AWS",
            "Azure",
            "GCP",
            "DigitalOcean",
            "Linode",
            "OVHcloud",
            # Social & Media
            "TikTok",
            "ByteDance",
            "Snap",
            "Telegram",
            "WhatsApp",
            "Instagram",
            "Medium",
            "Substack",
            "Patreon",
            # E-commerce
            "Shopify",
            "Etsy",
            "eBay",
            "Wayfair",
            "Chewy",
            "Rakuten",
            "Alibaba",
            "Tencent",
            # Rideshare & Delivery
            "Postmates",
            "Grubhub",
            "Deliveroo",
            "Gopuff",
            "Getir",
            # Fintech
            "Wise",
            "Revolut",
            "N26",
            "Monzo",
            "Starling Bank",
            "SoFi",
            "Marqeta",
            # Cybersecurity
            "CrowdStrike",
            "Palo Alto Networks",
            "Zscaler",
            "Okta",
            "SentinelOne",
            "Wiz",
            "Snyk",
            "Lacework",
            # More major tech companies
            "Cisco",
            "Dell",
            "HP",
            "Lenovo",
            "Samsung",
            "Sony",
            "LG",
            "Panasonic",
            "Siemens",
            "Bosch",
            "GE",
            "3M",
            "Honeywell",
            "Raytheon",
            "Lockheed Martin",
            "Boeing",
            "Northrop Grumman",
            # More financial institutions
            "Deutsche Bank",
            "HSBC",
            "BNP Paribas",
            "Societe Generale",
            "RBC",
            "TD Bank",
            "Scotiabank",
            "BMO",
            "PNC",
            "Capital One",
            "Discover",
            "American Express",
            "Visa",
            "Mastercard",
            # Insurance & financial services
            "Allstate",
            "State Farm",
            "Progressive",
            "Geico",
            "MetLife",
            "Prudential",
            "AIG",
            "Berkshire Hathaway",
            # More tech & software
            "Red Hat",
            "SUSE",
            "Canonical",
            "VMware",
            "Citrix",
            "Nutanix",
            "Pure Storage",
            "NetApp",
            "EMC",
            "HPE",
            "Arista Networks",
            "Juniper Networks",
            "F5 Networks",
            "Fortinet",
            "Check Point",
            "Symantec",
            "McAfee",
            "Trend Micro",
            "Kaspersky",
            # Consulting & services
            "Accenture",
            "Deloitte",
            "PwC",
            "EY",
            "KPMG",
            "Capgemini",
            "Cognizant",
            "Infosys",
            "TCS",
            "Wipro",
            "HCL",
            "Tech Mahindra",
            "DXC Technology",
            "CGI",
            "Atos",
            # More SaaS & cloud
            "Box",
            "Dropbox",
            "DocuSign",
            "Zoom",
            "RingCentral",
            "Vonage",
            "8x8",
            "Five9",
            "Genesys",
            "Nice",
            "Verint",
            # E-learning & education tech
            "Coursera",
            "Udemy",
            "Khan Academy",
            "Duolingo",
            "Chegg",
            "Pearson",
            "McGraw Hill",
            "Blackboard",
            "Canvas",
            "D2L",
            # Healthcare tech
            "Epic Systems",
            "Cerner",
            "Allscripts",
            "McKesson",
            "Change Healthcare",
            "Optum",
            "CVS Health",
            "Anthem",
            "UnitedHealth",
            "Humana",
            "Cigna",
            # Automotive
            "Ford",
            "GM",
            "Stellantis",
            "Toyota",
            "Honda",
            "Nissan",
            "Hyundai",
            "Kia",
            "BMW",
            "Mercedes",
            "Volkswagen",
            "Audi",
            "Porsche",
            "Volvo",
            "Rivian",
            "Lucid Motors",
            "Polestar",
            # Semiconductor
            "AMD",
            "ARM",
            "Broadcom",
            "Marvell",
            "Micron",
            "Western Digital",
            "Seagate",
            "Texas Instruments",
            "Analog Devices",
            "NXP",
            "Infineon",
            "STMicroelectronics",
            "Renesas",
            "MediaTek",
            "TSMC",
            # Telecommunications
            "Verizon",
            "AT&T",
            "T-Mobile",
            "Sprint",
            "Comcast",
            "Charter",
            "Cox",
            "Dish",
            "Vodafone",
            "Orange",
            "Telefonica",
            "BT Group",
            # Retail & logistics
            "Costco",
            "Best Buy",
            "Home Depot",
            "Lowes",
            "Kroger",
            "Albertsons",
            "CVS",
            "Walgreens",
            "FedEx",
            "UPS",
            "DHL",
            "USPS",
            # Media & entertainment
            "Disney",
            "Warner Bros",
            "Paramount",
            "Universal",
            "Sony Pictures",
            "HBO",
            "Hulu",
            "Peacock",
            "ESPN",
            "NFL",
            "NBA",
            "MLB",
            # Travel & hospitality
            "Expedia",
            "Booking.com",
            "Priceline",
            "TripAdvisor",
            "Marriott",
            "Hilton",
            "Hyatt",
            "IHG",
            "Airbnb",
            # Energy & utilities
            "ExxonMobil",
            "Chevron",
            "Shell",
            "BP",
            "ConocoPhillips",
            "Schlumberger",
            "Halliburton",
            "Baker Hughes",
            # Aerospace & defense
            "Airbus",
            "BAE Systems",
            "L3Harris",
            "Textron",
            "General Dynamics",
            # More fintech
            "Adyen",
            "Checkout.com",
            "Paxos",
            "Circle",
            "Chainalysis",
            "Ledger",
            "Gemini",
            "Kraken",
            "Binance",
            "FTX",
            # More enterprise software
            "Atlassian",
            "Jira",
            "Confluence",
            "Smartsheet",
            "Airtable",
            "ClickUp",
            "Trello",
            "Basecamp",
            "Wrike",
            "TeamViewer",
            "LogMeIn",
            "GoToMeeting",
            # More cybersecurity
            "Tenable",
            "Rapid7",
            "Qualys",
            "Carbon Black",
            "Tanium",
            "Darktrace",
            "Vectra AI",
            "Cylance",
            # Adtech & martech
            "Google Ads",
            "Meta Ads",
            "The Trade Desk",
            "Criteo",
            "Taboola",
            "Outbrain",
            "Adobe Marketing Cloud",
            "Salesforce Marketing Cloud",
            "HubSpot",
            "Marketo",
            "Eloqua",
            "Mailchimp",
            "Constant Contact",
            "SendGrid",
            # More AI/ML companies
            "DeepMind",
            "Wayve",
            "Character.AI",
            "Jasper",
            "Copy.ai",
            "Synthesia",
            "Replicate",
            "Together AI",
            "Perplexity",
            "Glean",
            "Harvey",
            "Adept",
            # More infrastructure
            "Terraform",
            "Ansible",
            "Puppet",
            "Chef",
            "Jenkins",
            "CircleCI",
            "Travis CI",
            "GitLab CI",
            "GitHub Actions",
            "ArgoCD",
            "Flux",
            # Databases & analytics
            "Databricks",
            "dbt Labs",
            "Fivetran",
            "Airbyte",
            "Rudderstack",
            "Hightouch",
            "Census",
            "Looker",
            "Tableau",
            "Power BI",
            "Qlik",
            "Sisense",
            "ThoughtSpot",
            "Mode Analytics",
            # Developer tools
            "JetBrains",
            "Postman",
            "Insomnia",
            "Sentry",
            "Bugsnag",
            "Rollbar",
            "LogRocket",
            "FullStory",
            "Hotjar",
            "Optimizely",
            "LaunchDarkly",
            # Gaming
            "Supercell",
            "King",
            "Zynga",
            "Playrix",
            "miHoYo",
            "Niantic",
            "Bungie",
            "Rockstar",
            "Bethesda",
            "Square Enix",
            "Capcom",
            "Bandai Namco",
            "Nintendo",
        ],
    )

    scraper = ResumeScraper(search_config=config, download_dir="./downloads")
    scraper.run(max_queries=None)  # Run ALL queries (all companies)

    # Option 2: Use custom SearchConfig for more control
    # from scraper import ResumeScraper
    #
    # config = SearchConfig(
    #     job_titles=["machine learning engineer"],
    #     seniority_levels=["senior", "staff"],
    #     companies=["Google", "Meta"],
    #     file_types=["pdf"],  # Only search PDFs
    #     results_per_query=10,
    #     exclude_terms=["template", "example", "sample"]
    # )
    #
    # scraper = ResumeScraper(search_config=config, download_dir="./downloads")
    # scraper.run(max_queries=10)
